#include "Menu.h"

#include "../Core/Renderer/ConsoleColours.h"

//exit button sprite
CHAR_INFO exitSprite[] =
{
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK}, {' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},
};

//play button sprite
CHAR_INFO playSprite[] =
{
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ',BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},

};

//title sprite
CHAR_INFO TitleSprite[] =
{
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ',BACKGROUND_WHITE}, {' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_BLACK}, {' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_BLACK}, {' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
	{' ', BACKGROUND_BLACK}, {' ', BACKGROUND_WHITE}, {' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},{' ', BACKGROUND_BLACK},{' ', BACKGROUND_WHITE},
};

//CONSTRUCTOR 
MenuIcon::MenuIcon()
	: m_bInitialised(false)
{
}

// DESTRUCTOR
MenuIcon::~MenuIcon()
{
}

//gives variable for x and y to be used in code
void MenuIcon::SetPosition(Vector2 position)
{
	m_position.x = position.x;
	m_position.y = position.y;
}

//gets the position of the menu item and returns it
Vector2 MenuIcon::GetPosition()
{
	return m_position; 
}

//sets position of menu icons into correct places
void MenuIcon::Initialise(Vector2& position)
{
	switch (GetSpriteID()) {
	case 0:Sprite::Initialise(TitleSprite, GetPosition()); break;
	case 1:Sprite::Initialise(playSprite, GetPosition()); break;
	case 2:Sprite::Initialise(exitSprite, GetPosition()); break;
	}

	Vector2 startPosition(position.x - (Sprite::GetSize().x / 2),
		position.y - (Sprite::GetSize().y / 2));
	Sprite::SetPosition(startPosition);
	m_bInitialised = true;
}
//calls renderer and renders all of the sprites
void MenuIcon::Render(ASCIIRenderer* pRenderer)
{
	if (!m_bInitialised)
		return;
	Sprite::Render(pRenderer);
}
void MenuIcon::Update()
{
	if (!m_bInitialised || !m_Active)
		return;
}
//pointer sprite
CHAR_INFO pointerSprite[] =
{
	{0, BACKGROUND_BLACK}, {0, BACKGROUND_BLACK},{0, BACKGROUND_RED},
	{0, BACKGROUND_BLACK}, {0, BACKGROUND_RED},{0, BACKGROUND_BLACK},
	{0, BACKGROUND_RED}, {0, BACKGROUND_BLACK},{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK}, {0, BACKGROUND_RED},{0, BACKGROUND_BLACK},
	{0, BACKGROUND_BLACK}, {0, BACKGROUND_BLACK},{0, BACKGROUND_RED},

};

//pointer constructor
Pointer::Pointer()
	:m_upKey(0)
	, m_downKey(0)
	, m_bInitialised(false)
{
}

//pointer destuctor
Pointer::~Pointer()
{
}

void Pointer::Initialise(Vector2& position, int upKey, int downKey)
{
	m_upKey = upKey;
	m_downKey = downKey;

	Sprite::Initialise(pointerSprite, Vector2(3, 5));
	Vector2 startPosition(position.x - (Sprite::GetSize().x / 2),
		position.y - (Sprite::GetSize().y / 2));
	SetPosition(startPosition);
	m_bInitialised = true;
}

//if UP key is pressed, move the pointer up so its next to 'play'. if the down key is pressed, move it down so its next to 'exit'
void Pointer::Update()
{
	if (!m_bInitialised)
		return;

	if (GetKeyState(m_upKey) < 0)
	{
		MoveUp();
	}
	if (GetKeyState(m_downKey) < 0)
	{
		MoveDown();
	}


}
void Pointer::Render(ASCIIRenderer* pRenderer)
{
	if (!m_bInitialised)
		return;

	Sprite::Render(pRenderer);
}
// sets y coordinate to same as play icon
void Pointer::MoveUp()
{
	SetPosition(Vector2(SCREEN_WIDTH / 2 + 20, (SCREEN_HEIGHT / 2) - 2));

}
//sets y coordinate so its next to exit icon
void Pointer::MoveDown()
{
	SetPosition(Vector2(SCREEN_WIDTH / 2 + 20, SCREEN_HEIGHT / 2 + 4));
}